# volumes:
#   web_data:
#   mysql_data:
#     driver: local # Define the driver and options under the volume name
#     driver_opts:
#       type: none
#       device: ${DOCKER_DATA_LOCATION}/mysql_data
#       o: bind
#   lorekeeper_mnt:
#     driver: local
#     driver_opts:
#       type: none
#       device: ./
#       o: bind

volumes:
  mysql_data:
  lorekeeper_mnt:
    driver: local
    driver_opts:
      type: none
      device: ./
      o: bind
  minio_data:

networks:
  default:
    name: lorekeeper_network

services:
  lorekeeper_db:
    image: mariadb:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    ports:
      - ${DB_PORT}:3306
    volumes:
      - mysql_data:/var/lib/mysql

  lorekeeper_phpmyadmin:
    env_file:
    - .env
    -  docker/LK_docker.env
    image: phpmyadmin:latest
    environment:
      PMA_HOST: lorekeeper_db
      PMA_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - lorekeeper_db
    ports:
      - ${PHPMYADMIN_PORT}:80

  lorekeeper_front:
    env_file:
      - .env
      -  docker/LK_docker.env
    build: ./docker/Dockerfile
    depends_on:
      - lorekeeper_db
      - maildev
    environment:
      - APACHE_DOCUMENT_ROOT:/var/www/public
    ports:
      - ${FRONTEND_PORT}:80

  maildev:
    image: maildev/maildev
    ports:
      - "1080:1080"
    expose:
      - 1025/tcp

  minio:
    image: docker.io/bitnami/minio:2022
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=your_username
      - MINIO_ROOT_PASSWORD=your_pasword
      - MINIO_DEFAULT_BUCKETS=your_bucket_name
