volumes:
  web_data:
  mysql_data:
    driver: local # Define the driver and options under the volume name
    driver_opts:
      type: none
      device: ./.docker/mysql_data
      o: bind
  lorekeeper_mnt:
    driver: local
    driver_opts:
      type: none
      device: ./
      o: bind

services:
  lorekeeper_db:
    image: mariadb:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    ports:
      - ${DB_PORT}:3306
    volumes:
      - mysql_data:/var/lib/mysql

  lorekeeper_phpmyadmin:
    env_file:
    - .env
    -  LK_docker.env
    image: phpmyadmin:latest
    environment:
      PMA_HOST: lorekeeper_db
      PMA_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - lorekeeper_db
    ports:
      - ${PHPMYADMIN_PORT}:80
    links:
      - lorekeeper_db

  lorekeeper_front:
    env_file:
      - .env
      -  LK_docker.env
    build: .
    develop:
      watch:
        - action: sync
          path: ./
          target: /var/www
    links:
      - lorekeeper_db
    depends_on:
      - lorekeeper_db
    environment:
      - APACHE_DOCUMENT_ROOT:/var/www/public
    ports:
      - ${FRONTEND_PORT}:80
